#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v3
# autospec commit: 750e50d
#
Name     : perl-match-simple
Version  : 0.012
Release  : 5
URL      : https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/match-simple-0.012.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/match-simple-0.012.tar.gz
Summary  : 'simplified clone of smartmatch operator'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-match-simple-license = %{version}-%{release}
Requires: perl-match-simple-perl = %{version}-%{release}
Requires: perl(Exporter::Tiny)
Requires: perl(Sub::Infix)
BuildRequires : buildreq-cpan
BuildRequires : perl(Exporter::Tiny)
BuildRequires : perl(Sub::Infix)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Try::Tiny)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
match::simple - simplified clone of smartmatch operator
SYNOPSIS
use v5.10;
use match::simple;

if ( $this |M| $that ) {
say "$this matches $that";
}

%package dev
Summary: dev components for the perl-match-simple package.
Group: Development
Provides: perl-match-simple-devel = %{version}-%{release}
Requires: perl-match-simple = %{version}-%{release}

%description dev
dev components for the perl-match-simple package.


%package license
Summary: license components for the perl-match-simple package.
Group: Default

%description license
license components for the perl-match-simple package.


%package perl
Summary: perl components for the perl-match-simple package.
Group: Default
Requires: perl-match-simple = %{version}-%{release}

%description perl
perl components for the perl-match-simple package.


%prep
%setup -q -n match-simple-0.012
cd %{_builddir}/match-simple-0.012
pushd ..
cp -a match-simple-0.012 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-match-simple
cp %{_builddir}/match-simple-%{version}/COPYRIGHT %{buildroot}/usr/share/package-licenses/perl-match-simple/6e40016ca1e74fbc307cd82ba48ea4763dfb2954 || :
cp %{_builddir}/match-simple-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-match-simple/5a940e197f940adc741045d885217f7a1a8e0078 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/match::simple.3
/usr/share/man/man3/match::simple::sugar.3
/usr/share/man/man3/match::smart.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-match-simple/5a940e197f940adc741045d885217f7a1a8e0078
/usr/share/package-licenses/perl-match-simple/6e40016ca1e74fbc307cd82ba48ea4763dfb2954

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
